pipeline {
	agent any

	environment {
		IMAGE_NAME = 'jenkins-demo'
	}

	stages {
		stage('Build Maven') {
			agent {
				docker {
					image 'maven:3.9.11-eclipse-temurin-21-noble'
					args '-v /root/.m2:/root/.m2'
				}
			}
			steps {
				sh 'mvn -B -DskipTests clean package'
				stash name: 'app-jar', includes: 'target/*.jar'
			}
		}



		stage('Build Docker Image') {
			steps {
				unstash 'app-jar'
				script {
					def appImage = docker.build("${IMAGE_NAME}:${BUILD_NUMBER}")
					appImage.tag("${IMAGE_NAME}:latest")
				}
			}
		}

		stage('Push Docker Image') {
			steps {
				script {
					docker.withRegistry("${DOCKER_REGISTRY}", "${DOCKER_REGISTRY_CREDENTIALS}") {
						docker.image("${IMAGE_NAME}:${BUILD_NUMBER}").push()
						docker.image("${IMAGE_NAME}:latest").push()
					}
				}
			}
		}

		stage('Deploy to Kubernetes') {
			steps {
				script {
					withCredentials([file(credentialsId: "${KUBECONFIG_CREDENTIALS_FILE}", variable: 'KUBECONFIG')]) {
						sh """
								kubectl --kubeconfig=${KUBECONFIG} set image deployment/${IMAGE_NAME} \
									${IMAGE_NAME}=${DOCKER_REGISTRY}/${IMAGE_NAME}:${BUILD_NUMBER}
								kubectl --kubeconfig=${KUBECONFIG} rollout status deployment/${IMAGE_NAME}
							"""
					}
				}
			}
		}
	}
}